server:
  port: 8082

spring:
  #mysql
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: kaige520
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

mybatis:
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.pipikai.domain
  mapper-locations: classpath:mappers/*.xml
#  type-handlers-package: com.pipikai.dao

